### ISSUE TITLE
Fetch for domian objects that in ValueObject types doesn't work

### ISSUE THREAD

**Issue by llotall** [Luxoft/gengen#117]
**Describe the bug**
For example, we have class that has value object type property

```csharp
public class DomainClass1 : AuditPersistentDomainObjectBase 
{
    public virtual Component? Component { get; set; }
}

// where Component is 
public class Component : ValueObject
{
    public virtual DomainClass2? DomainClass2 { get; protected set; }
}
```
And fetch for this classes structure doesn't work, inspite on Nnhibernate Support.

```csharp
...
bll.GetUnsecureQueryable(f => f.SelectNested(x => x.Component ).Select(x => x!.DomainClass2)).ToList();
...
```
As result low performance and big amount of useless requests.

**To Reproduce**
For reproducing use same classes structure as described above

**Expected behavior**
Fetch must work, amount of requests to database must decrease

**Comment by sevaru** [comment]
I don't think it's relate to GenGen repo :)
could you clarify please ?

**Comment by llotall** [comment]
> I don't think it's relates to GenGen repo :) could you clarify please ?

Lol, please excuse me))
