### ISSUE TITLE
Develop policy for creating and using secrets in Luxoft repos

### ISSUE THREAD

**Issue by jeremiah** [Luxoft/gengen#18]
**Is your feature request related to a problem? Please describe.**
The goal is to publish gengen to npmjs.org to include it in the Node ecosystem of packages. To do so we need to have an authorization token from Node. 

**Describe the solution you'd like**
We need to establish a policy for handling secrets in general and for npmjs.org specifically. Reusing GitHub's [secrets API](https://docs.github.com/en/free-pro-team@latest/rest/reference/actions#secrets) seems like a good approach and ought to be evaluated.

**Comment by aleshchev** [comment]
Hi Jeremiah,

We created NPM account for BSS department. And now we already pushed first package https://www.npmjs.com/package/@luxbss/gengen. 

P.S.
We uses standart github CI/CD approach.
