### ISSUE TITLE
Incorrect relative path if app has baseHref that different then /

### ISSUE THREAD

**Issue by aegoroff** [Luxoft/gengen#62]
**Describe the bug**
The tool generates relative paths which is not correct if application has baseHref (you can see it in base element) different then simple slash (/)

**To Reproduce**
Just run ng build --prod --base-href /somePath/

**Expected behavior**
Tool generates relative paths something like **/somePath/api/v1/Something**

**Actual behavior**
Tool generates relative paths  **/api/v1/Something**

**Comment by aleshchev** [comment]
Hi @aegoroff,

The issue is duplicated by https://github.com/Luxoft/gengen/issues/56.

**Comment by aleshchev** [comment]
#56
